version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - APP_PORT=3002
      - SWAGGER_API_URL=http://localhost:3002
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - JWT_SECRET=JWT_SECRET
      - JWT_EXPIRES_IN=3600s
      - JWT_REFRESH_TOKEN_SECRET=refresh_token_secret
      - JWT_REFRESH_TOKEN_EXPIRES_IN=3600s
      - JWT_FIRST_ACCESS_SECRET=first_access_token_secret
      - JWT_FIRST_ACCESS_EXPIRES_IN=3600s
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app  
      - /usr/src/app/node_modules 

  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_PORT=3000
      - TZ=America/Manaus
    volumes:
      - ./frontend:/app 
      - /app/node_modules 

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: